### PR TITLE
ES 2.0 compatibility for 4.1.2

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This pull-request integrate changes, which allow running kibana-static against Elasticsearch 2.0. This pull request makes the Kibana instance operational on the dashboards we had.
- [x] - Enforce the max_result_window value (would be better to migrate the scrolling support)
- [x] - Bundle angular JS packages (the scope could be reduced)
- [x] - Fix date range queries (https://github.com/elastic/kibana/commit/82ed343b76947e55d164c511d19e2d2b9e13100b)
- [x] - Port the FetchStrategyForSearch implementation from 4.4.2

@Asimov4 Would be such partial fix an applicable solution for kibana-static? Due to the major repo changes in 4.2..4.4, it will be hard to integrate the new data structure. I've started this activity, but there is no ETA. From what I see, kibana-4.1.2 has not been migrated completely as well.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @reviewbybees. Current status - work-in-progress

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by Asimov4** [comment]
The changes make sense. I can tag this as a new version for people to download.

**Comment by MoveAlong** [comment]
Can I ask about 20617b94fa0aa6f3b1ef860f706c2fb8ca7bce38 ? 

It conflicts with an internal patch I have to support rest.action.multi.allow_explicit_index: false

Is there something that requires the promises here? I see the fix for no indices, but beyond that, is the conversion to promises necessary? It looks like they all resolve statically. 

Thanks!

**Comment by oleg-nenashev** [comment]
> Is there something that requires the promises here? I see the fix for no indices, but beyond that, is the conversion to promises necessary? It looks like they all resolve statically. 

IIRC it was required to patch this method, because there were failures in ES2.0. So I've taken the method from the latest Kibana version. It worked. I do not recall if the issue was related to Promises

**Comment by MoveAlong** [comment]
I'm running with 2.0, with the old code, but I don't know if there's something that will bite me later on, if I don't change it. I've run through  "Getting Started with Kibana" with no problems. 

If you happen to recall what the issue was, I'd appreciate the info.

**Comment by rayenyang** [comment]
@Asimov4 @oleg-nenashev I need the version which is not bundled,could anybody help? thx

**Comment by oleg-nenashev** [comment]
@rayenyang WDYM?

**Comment by rayenyang** [comment]
@oleg-nenashev I am sorry that I did not express my problem properly! In other words, I need this version you contributed,but not a big file of index.js

**Pull request merged**
